# Generated by Django 5.1.5 on 2025-02-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_category_active_alter_category_name_and_more"),
        ("language", "0003_categorytranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorytranslation",
            name="name",
            field=models.CharField(help_text="Name of the category", max_length=255),
        ),
        migrations.CreateModel(
            name="CategorySchemaTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON representation of the schema. Types: [str, int, float, bool]. Example: {'color': {'type': 'str', 'required': true}, 'size': {'type': 'int'}}",
                        null=True,
                    ),
                ),
                (
                    "category_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="category.categoryschema",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.language",
                    ),
                ),
            ],
            options={
                "unique_together": {("category_schema", "language")},
            },
        ),
    ]
