# Generated by Django 5.2 on 2025-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0004_alter_categorytranslation_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={"verbose_name": "Language", "verbose_name_plural": "Languages"},
        ),
        migrations.AlterField(
            model_name="categoryschematranslation",
            name="schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON representation of the schema key related to primary language of schema.Example: {'color': 'колір', 'size': 'розмір'}",
                null=True,
            ),
        ),
    ]
