# Generated by Django 5.1.5 on 2025-01-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
