# Generated by Django 5.1.5 on 2025-01-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_description_product_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="date_added",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
