# Generated by Django 5.1.5 on 2025-01-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_date_added_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="property",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
