# Generated by Django 5.1.5 on 2025-01-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="property",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
