# Generated by Django 5.1.5 on 2025-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_categoryschema_options_and_more"),
        ("product", "0005_alter_product_property"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-updated_at"], name="product_pro_updated_adb9f5_idx"
            ),
        ),
    ]
