# Generated by Django 5.1.5 on 2025-01-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_categoryschema_options_and_more"),
        ("product", "0006_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="product_pro_categor_2b9d78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_pro_name_b60cd1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="product_pro_price_3acd1d_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name", "price"], name="product_pro_name_cf72e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "name", "price"],
                name="product_pro_categor_9a10cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(models.Q(("active", True)), name="active_products_idx"),
        ),
    ]
