# Generated by Django 5.1.5 on 2025-01-22 22:15

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_product_product_pro_categor_2b9d78_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=product.models.generate_upload_to),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product"], name="product_pro_product_20de7e_idx"
                    )
                ],
                "unique_together": {("product", "image")},
            },
        ),
    ]
