# Generated by Django 5.1.5 on 2025-01-23 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_category_active_alter_category_name_and_more"),
        ("product", "0008_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="productimage",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True, help_text="Is the product active?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Category of the product",
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(auto_now_add=True, help_text="Creation date"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the product", null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(help_text="Name of the product", max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.CharField(
                blank=True, help_text="Owner of the product", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the product, format: 0.00",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="property",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Property of the product. Example: {'color': 'red', 'size': 34}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last updated date and time"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="product.product",
            ),
        ),
    ]
