# Generated by Django 5.1.5 on 2025-02-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_productimage_description_productimage_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
