# Generated by Django 5.2 on 2025-04-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "category",
            "0006_alter_category_options_alter_categoryschema_category_and_more",
        ),
        ("product", "0010_product_sku"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is the product active?", verbose_name="Active"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Category of the product",
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, help_text="Creation date", verbose_name="Created"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the product",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Name of the product", max_length=255, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.CharField(
                blank=True,
                help_text="Owner of the product",
                max_length=255,
                null=True,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Price of the product, format: 0.00",
                max_digits=10,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="property",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Property of the product. Example: {'color': 'red', 'size': 34}",
                null=True,
                verbose_name="Property",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="Stock Keeping Unit of the product",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last updated date and time",
                verbose_name="Updated",
            ),
        ),
    ]
