# Generated by Django 5.1.5 on 2025-01-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_categoryschema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryschema",
            name="schema",
        ),
        migrations.AddField(
            model_name="categoryschema",
            name="properties",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
