# Generated by Django 5.1.5 on 2025-01-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_remove_categoryschema_schema_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryschema",
            options={
                "verbose_name": "Category Schema",
                "verbose_name_plural": "Category Schemas",
            },
        ),
        migrations.RenameField(
            model_name="categoryschema",
            old_name="properties",
            new_name="schema",
        ),
    ]
