# Generated by Django 5.1.5 on 2025-01-23 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_alter_categoryschema_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Is the category active?"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(help_text="Name of the category", max_length=255),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category. Null if it's a root category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
        migrations.AlterField(
            model_name="categoryschema",
            name="schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON representation of the schema. Types: [str, int, float, bool]. Example: {'color': {'type': 'str', 'required': true}, 'size': {'type': 'int'}}",
                null=True,
            ),
        ),
    ]
