# Generated by Django 5.2 on 2025-04-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_alter_category_active_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="categoryschema",
            name="category",
            field=models.OneToOneField(
                help_text="Category associated with the schema",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schema",
                to="category.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="categoryschema",
            name="schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON representation of the schema. Types: [str, int, float, bool]. Example: {'color': {'type': 'str', 'required': true}, 'size': {'type': 'int'}}",
                null=True,
                verbose_name="Schema",
            ),
        ),
    ]
