
name: DEPLOY

permissions:
  contents: read
  pull-requests: write

# on:
#   workflow_run:
#     workflows: ["Django CI"]
#     types:
#       - completed

on:
  pull_request:
  push:
    branches: [ dev-lexxai, dev ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        # Only run this step if the branch is main
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
