# workflow triggers
on:
  push:
    branches: [ dev-lexxai, dev-lexxai-product ]
  pull_request:
    branches: [ dev-lexxai, dev-lexxai-product  ]
  workflow_dispatch:

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
